### ISSUE TITLE
Fails to build on Fedora 23 with Ruby 2.2.4p230 

### ISSUE THREAD

**Issue by MJoergen** [Dahrkael/rENet#7]
I get the following build error:

```
unix.c:52:13: error: conflicting types for »socklen_t«
 typedef int socklen_t;
             ^
In file included from /usr/include/sys/socket.h:38:0,
                 from unix.c:8:
/usr/include/bits/socket.h:33:21: note: previous declaration of »socklen_t« was here
 typedef __socklen_t socklen_t;

```

**Comment by cyberarm** [comment]
Commenting out this line https://github.com/Dahrkael/rENet/blob/master/ext/renet/unix.c#L52 seems to fix this issue. (Ubuntu 16.04 x64)
